Models/CreateTrainingViewModel.cs
namespace Training.Models
{
    public class CreateTrainingViewModel
    {
        public List<Ovning> Exercises { get; set; }
        public MyTrainings Training { get; set; }
        public string Exercise { get; set; }   





    }
}

Models/ErrorViewModel.cs
namespace Training.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MyTrainings.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using MongoDB.Bson;

namespace Training.Models
{
    public class MyTrainings
    {

        public ObjectId Id { get; set; }
        public string Exercise { get; set; }
        public DateTime Date { get; set; }

        public List<SelectListItem> Exerc { set; get; }

        public int Distance { get; set; }
    }
}

Models/Ovning.cs
using MongoDB.Bson;
using System;

namespace Training.Models
{
    public class Ovning
    
      {
        public ObjectId Id { get; set; }
        public string Title { get; set; }

        public string Description { get; set; }

       
    }
}

Controllers/ExerciseController.cs
using Microsoft.AspNetCore.Mvc;
using Training.Models;

namespace Training.Controllers
{
    public class ExerciseController : Controller
    {
        public async Task<IActionResult> Index()
        {
            Database db = new Database();
            var exercises = await db.GetOvningarAsync();
            return View(exercises);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Ovning ovning)
        {
            Database db = new Database();
            await db.SaveExercise(ovning);
            return Redirect("/Exercise");
        }

        public async Task<IActionResult> Delete(string id)
        {
            Database db = new Database();
            var exercise = await db.GetExerciseById(id);
            return View(exercise);

        }
        [HttpPost]
        public async Task<IActionResult> DeleteExercise(string id)
        {
            Database db = new Database();
            await db.DeleteExercise(id);
            return Redirect("/Exercise");

        }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Training.Models;

namespace Training.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TrainingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Training.Models;

namespace Training.Controllers
{
    public class TrainingController : Controller
    {
       
            public async Task<IActionResult> Index()
            {
            
                Database db = new Database();
            var mytraining = await db.GetTrainingsAsync(); 
            
                return View(mytraining);
           
            }
        public async Task<IActionResult> Create()
        {
            Database db = new Database();
            var exercises = await db.GetOvningarAsync();
            var viewModel = new CreateTrainingViewModel()
            {
                Exercises = exercises,
            };
            return View(viewModel);

                }

        [HttpPost]
        public async Task<IActionResult> Create(MyTrainings training)
        {
            Database db = new Database();
            await db.SaveTraining(training);
            return Redirect("/Training");
        }

       


    }
}

Views/Exercise/Create.cshtml
@model Training.Models.Ovning

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Exercise</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Exercise/Delete.cshtml
@model Training.Models.Ovning

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ovning</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="DeleteExercise" asp-route-id="@Model.Id.ToString()">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Exercise/Index.cshtml
@model IEnumerable<Training.Models.Ovning>

@{
    ViewData["Title"] = "Index";
}

<h1>Add Exercise!</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.Id.ToString() })
              
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to your training app!</h1>
    <p>On Exercises you can add exercises. After your training go to Training history and write when you did the exercise and distance.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Training</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Training.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Training</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exercise" asp-action="Index">Exercises</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Training" asp-action="Index">Training History</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Training - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Training/Create.cshtml
@model Training.Models.CreateTrainingViewModel

@{
    ViewData["Title"] = "Create";
}





@{
    ViewData["Title"] = "Create";

    var selectList = Model.Exercises.Select(o => new SelectListItem
            {
                Text = o.Title,
                Value = o.Title

            }).ToList();
}


<h1>Create Training</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form">
                <label asp-for="Training.Exercise" class="control-label"></label>
                <select asp-for="Training.Exercise" class="form-control" asp-items="selectList"></select> 
                <span asp-validation-for="Training.Exercise" class="text-danger"></span>

                <label asp-for="Training.Date" class="control-label"></label>
                <input value="Date"  asp-for="Training.Date" />
                <span asp-validation-for="Training.Date" class="text-danger"></span>

                <label asp-for="Training.Distance" class="control-label"></label>
                <input type="number" value="Distance" asp-for="Training.Distance" />
                <span asp-validation-for="Training.Distance" class="text-danger"></span>

            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<style>
    .form {
        display: flex;
        gap: 20px;
        flex-wrap: wrap;
        flex-direction: column
    }
</style>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Training/Index.cshtml
@model IEnumerable<Training.Models.MyTrainings>

@{
    ViewData["Title"] = "Index";
}

<h1>Training History</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Exercise)
              
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Distance)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Exercise)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Distance)
            </td>
            <td>
            
            </td>
        </tr>
}
    </tbody>
</table>